//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoAbsenSKI {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MessageResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AutoAbsenSKI.MessageResources", typeof(MessageResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading chromium....
        /// </summary>
        internal static string DownloadChromiumStart {
            get {
                return ResourceManager.GetString("DownloadChromiumStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading chromium....
        /// </summary>
        internal static string DownloadChromiumStatus {
            get {
                return ResourceManager.GetString("DownloadChromiumStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate report without sending it.
        /// </summary>
        internal static string DryRunCommandDescription {
            get {
                return ResourceManager.GetString("DryRunCommandDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launching a new instance of Chromium....
        /// </summary>
        internal static string GenerateReportLaunching {
            get {
                return ResourceManager.GetString("GenerateReportLaunching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging in....
        /// </summary>
        internal static string GenerateReportLoggingIn {
            get {
                return ResourceManager.GetString("GenerateReportLoggingIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging out....
        /// </summary>
        internal static string GenerateReportLoggingOut {
            get {
                return ResourceManager.GetString("GenerateReportLoggingOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving report....
        /// </summary>
        internal static string GenerateReportScreenshot {
            get {
                return ResourceManager.GetString("GenerateReportScreenshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install Task Scheduler to send report automatically.
        /// </summary>
        internal static string InstallSchedulerCommandDescription {
            get {
                return ResourceManager.GetString("InstallSchedulerCommandDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured when creating task..
        /// </summary>
        internal static string InstallSchedulerError {
            get {
                return ResourceManager.GetString("InstallSchedulerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing scheduled task....
        /// </summary>
        internal static string InstallSchedulerInstalling {
            get {
                return ResourceManager.GetString("InstallSchedulerInstalling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheduled task currently supported on Windows-only..
        /// </summary>
        internal static string InstallSchedulerNotCompatible {
            get {
                return ResourceManager.GetString("InstallSchedulerNotCompatible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task installed successfully..
        /// </summary>
        internal static string InstallSchedulerSuccess {
            get {
                return ResourceManager.GetString("InstallSchedulerSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable headless browser.
        /// </summary>
        internal static string NoHeadlessCommandDescription {
            get {
                return ResourceManager.GetString("NoHeadlessCommandDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically create JIRA report for SKI administration and optionally create a scheduled task to automatically send report every 15th of each month..
        /// </summary>
        internal static string RootCommandDescription {
            get {
                return ResourceManager.GetString("RootCommandDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured when sending email..
        /// </summary>
        internal static string RootException {
            get {
                return ResourceManager.GetString("RootException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings has missing/invalid values. Run &apos;autoabsenski --settings&apos; to change settings..
        /// </summary>
        internal static string RootStatusInvalidState {
            get {
                return ResourceManager.GetString("RootStatusInvalidState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading settings....
        /// </summary>
        internal static string RootStatusLoading {
            get {
                return ResourceManager.GetString("RootStatusLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Composing email....
        /// </summary>
        internal static string SendEmailComposing {
            get {
                return ResourceManager.GetString("SendEmailComposing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending email....
        /// </summary>
        internal static string SendEmailSending {
            get {
                return ResourceManager.GetString("SendEmailSending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email sent at: {0}.
        /// </summary>
        internal static string SendEmailSent {
            get {
                return ResourceManager.GetString("SendEmailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialize/open settings.
        /// </summary>
        internal static string SettingsCommandDescription {
            get {
                return ResourceManager.GetString("SettingsCommandDescription", resourceCulture);
            }
        }
    }
}
